### ISSUE TITLE
Update blog post or this repo to use `dbt snapshot` instead of `dbt archive`

### ISSUE THREAD

**Issue by owenprough-sift** [dbt-labs/log-tables-example#3]
As far as I can tell, `dbt archive` was at some (distant) point in the past replaced with the `dbt snapshot` we all know and love. Can we update the blog post or this repo to mention snapshots?

This caused confusion today: https://getdbt.slack.com/archives/CBSQTAPLG/p1679510108353139

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
